### ISSUE TITLE
Paired-end sequencing in Skipper Manifest

### ISSUE THREAD

**Issue by yvazirabad** [YeoLab/skipper#15]
Hello,

I would like direction on how to incorporate paired-end eCLIP into the Skipper manifest. The example manifest indicates single-end sequencing with one or two lanes used. How do I add R1 and R2 to a single cell?

-Ibrahim Vazirabad

**Comment by augustboyle** [comment]
Hello,

I processed the paired end ENCODE data in two steps.

The paired end rule for making BAMs is on the Figshare: https://figshare.com/articles/dataset/Skipper_RNA-protein_interaction_profiles/21206009?file=37612190

Then, I started the GitHub pipeline from BAM input.

On starting from BAM input:
1) Edit the rule all so that the fastq specific output is not requested and it can generate all the needed output from BAMs.
2) Ensure that the informative read parameter is set appropriately, 1 if the crosslink site in in read 1 and 2 if the crosslink site is in read 2.

Another option is to simply use the informative read in the single end pipeline, which we have done when pooling samples on paired end sequencing runs. Because the Yeo lab library design is single end, we don’t make use of any of the read pairing information. In fact most of the reads are trimmed and it does not have any advantage at all. But if you have some larger fragments it could help with the alignment.

Best,
Evan

**Comment by FionaMoon** [comment]
So, I should just put Read2 in manifast instead of provide both R1 and R2 ?

**Comment by augustboyle** [comment]
Hello,

If you are processing ENCODE3 data then R2 encodes the crosslink site so that is the correct read to use.

If you are processing ENCODE4 data, it is single ended.

Other datasets may use R1 or R2 (or might have poor truncation signal altogether).

Evan

**Comment by FionaMoon** [comment]
Thank you for your reply!
I've checked my data and found the crosslink is in Read1.
I will try to run skipper only using R1.
