### ISSUE TITLE
analysis with only 1 SMI sample available

### ISSUE THREAD

**Issue by MSajek** [YeoLab/skipper#17]
Hi Evan,
I have one more question about running skipper. How should I get input coefficients with only one SMI (probably you have similar situation during encode data analysis). fit_input_betabinom.R requires input replicates and the following scripts relies on its output and I don't know how to deal with it with single SMI.
I will be grateful for any suggestions.
Best,

**Comment by augustboyle** [comment]
Hi Martin,You can use two CLIP replicates to estimate null overdispersion. In the config enter OVERDISPERSION_MODE=“clip”Either through the workflow or manually, you can then run fit_clip_betabinom.R instead of fit_input_betabinom.REvanCourtesy of my phoneOn Nov 15, 2023, at 3:12 PM, Marcin Sajek ***@***.***> wrote:﻿
Hi Evan,
I have one more question about running skipper. How should I get input coefficients with only one SMI (probably you have similar situation during encode data analysis). fit_input_betabinom.R requires input replicates and the following scripts relies on its output and I don't know how to deal with it with single SMI.
I will be grateful for any suggestions.
Best,

**Comment by MSajek** [comment]
Oh, I see, somehow I missed this information
