### ISSUE TITLE
Why are flank and shift used in this analysis pipeline?

### ISSUE THREAD

**Issue by VandaLovejoy** [YeoLab/skipper#38]
I'm trying to understand the rationale behind the use of bedtools flank and bedtools shift in this command sequence:

samtools cat {input.input_bams} | bedtools intersect -s -wa -a - -b {output.nt_census} | 
bedtools bamtobed -i - | awk '($1 != "chrEBV") && ($4 !~ "/{UNINFORMATIVE_READ}$")' | 
bedtools flank -s -l 1 -r 0 -g {CHROM_SIZES} -i - | 
bedtools shift -p 1 -m -1 -g {CHROM_SIZES} -i - | 
bedtools sort -i - | 
bedtools coverage -counts -s -a {output.nt_census} -b - | awk '{{print $NF}}' > {output.nt_input_counts};

How does this approach differ from skipping the flank and shift steps, as shown below?

samtools cat {input.input_bams} | bedtools intersect -s -wa -a - -b {output.nt_census} | 
bedtools bamtobed -i - | awk '($1 != "chrEBV") && ($4 !~ "/{UNINFORMATIVE_READ}$")' | 
bedtools sort -i - | 
bedtools coverage -counts -s -a {output.nt_census} -b - | awk '{{print $NF}}' > {output.nt_input_counts};

What specific role do flank and shift play in the analysis, and what kind of scenarios or data structures make their inclusion important? This seems to have a significant impact on the enrichment analysis later on.

**Comment by augustboyle** [comment]
Hello,

The flank and shift commands identify the end of the crosslinked read. Using the flank command alone has historically been more common to flag the crosslink site but this creates artifacts when aligned to the genome because it could misassign an exonic read as intronic if it crosses the junction (I confirmed that this happens at an infrequent but non-negligible rate).

If you were to continue the analyses without those steps, the counts would be massively inflated -- one read represents one crosslink event, not 20-50 or whatever the read length is -- so while the enrichment odds ratios might be reasonable, the p values would be artificially low.

**Comment by VandaLovejoy** [comment]
thank you for your explanation!
